spring:
  profiles:
    active: local

  application:
    name: auction


springdoc:
  api-docs:
    path: /api-docs # JSON 문서 경로 (기본값: /v3/api-docs)
  swagger-ui:
    path: /swagger-ui.html # UI 접속 경로 (기본값: /swagger-ui/index.html)
    groups-order: DESC # 태그 정렬 순서
    operations-sorter: method # HTTP Method 순으로 정렬
    disable-swagger-default-url: true
    display-request-duration: true # 요청 처리 시간 표시